language: java
jdk:
- oraclejdk11
notifications:
  slack: gridgo:7vQ2ec1IgZ0bjCN9w3wsUiIn
  
addons:
  sonarcloud:
    organization: "gridgo" # the key of the org you chose at step #3
    token: $SONAR_TOKEN

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean install sonar:sonar test jacoco:report coveralls:report -DrepoToken=$CoverallsRepoToken

# after_success:
# - mvn clean test jacoco:report coveralls:report -DrepoToken=$CoverallsRepoToken
