language: java
jdk:
- openjdk11
notifications:
  slack: gridgo:7vQ2ec1IgZ0bjCN9w3wsUiIn

services:
- mysql

addons:
  sonarcloud:
    organization: "gridgo" # the key of the org you chose at step #3
    token: $SONAR_TOKEN

script:
- mvn test jacoco:report

after_success:
- bash <(curl -s https://codecov.io/bash)
- "[[ $TRAVIS_BRANCH == \"develop\" ]] && { python travis/addServer.py; mvn -DskipTests=true clean deploy --settings ~/.m2/mySettings.xml; };"
